# Generated by Django 3.1.2 on 2020-10-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0012_auto_20201029_0007'),
        ('blog', '0014_auto_20201029_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='forecast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forecasts.forecast'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
    ]
