# Generated by Django 3.1.2 on 2020-10-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201030_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted']},
        ),
    ]
