# Generated by Django 3.1.2 on 2020-10-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forecast_points',
        ),
        migrations.AddField(
            model_name='profile',
            name='week_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
