# Generated by Django 3.1.2 on 2020-10-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201025_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
