# Generated by Django 3.1.2 on 2020-10-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_points',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
