# Generated by Django 3.2 on 2021-04-16 11:11
from social_django.models import UserSocialAuth

from django.db import migrations

from users.utils import set_user_avatar_from_url, transliterate_user


def update_fb_usernames_and_avatars(apps, schema_editor):
    socials = UserSocialAuth.objects.all()
    for social in socials:
        user = social.user
        picture_url = social.extra_data.get('picture', {}).get('data', {}).get('url')
        if picture_url and not user.profile.avatar:
            set_user_avatar_from_url(user, picture_url)
        transliterate_user(user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.RunPython(update_fb_usernames_and_avatars, reverse_code=migrations.RunPython.noop),
    ]
