# Generated by Django 3.1.2 on 2020-10-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoreboard', '0004_auto_20201020_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.season')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(blank='True', max_length=30)),
                ('home_logo', models.ImageField(upload_to='fixtures/')),
                ('guest_name', models.CharField(blank='True', max_length=30)),
                ('guest_logo', models.ImageField(upload_to='fixtures/')),
                ('home_goals', models.PositiveIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveIntegerField(blank=True, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.forecast')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='scoreboard.team')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='scoreboard.team')),
            ],
        ),
    ]
