# Generated by Django 3.1.2 on 2020-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_auto_20201023_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='week',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
