# Generated by Django 3.1.2 on 2020-10-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_forecast_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='away_goals',
            new_name='guest_goals',
        ),
    ]
