# Generated by Django 3.1.2 on 2020-10-23 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_auto_20201023_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 19, 21, 34, 915129, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
