# Generated by Django 3.1.2 on 2020-10-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_auto_20201024_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='results',
            field=models.JSONField(default=dict),
        ),
    ]
