# Generated by Django 3.1.2 on 2020-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0009_auto_20201024_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
