# Generated by Django 3.1.2 on 2020-10-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0011_prediction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-created_at']},
        ),
    ]
