# Generated by Django 3.1.3 on 2020-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0013_auto_20201030_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
