# Generated by Django 3.1.6 on 2021-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0015_auto_20210131_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
