# Generated by Django 3.1.6 on 2021-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0017_auto_20210202_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='week',
            field=models.CharField(max_length=64),
        ),
    ]
