# Generated by Django 3.1.2 on 2020-10-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='captain',
            field=models.BooleanField(default=None, null=True, unique=True),
        ),
    ]
