# Generated by Django 3.1.2 on 2020-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0004_player_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Воротар'), ('defender', 'Захисник'), ('midfielder', 'Півзахисник'), ('striker', 'Нападник'), ('manager', 'Тренер')], max_length=200),
        ),
    ]
