# Generated by Django 3.1.2 on 2020-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0005_auto_20201021_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('1', 'Воротар'), ('2', 'Захисник'), ('3', 'Півзахисник'), ('4', 'Нападник'), ('5', 'Тренер')], max_length=200),
        ),
    ]
