# Generated by Django 3.1.2 on 2020-10-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0007_auto_20201021_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveIntegerField(choices=[(1, 'Воротар'), (2, 'Захисник'), (3, 'Півзахисник'), (4, 'Нападник'), (5, 'Тренер')]),
        ),
    ]
