# Generated by Django 3.1.2 on 2020-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0008_auto_20201021_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_html', models.TextField()),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
