# Generated by Django 3.1.2 on 2020-10-21 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squad', '0009_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
