# Generated by Django 3.1.2 on 2020-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next',
            field=models.BooleanField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='prev',
            field=models.BooleanField(default=None, null=True, unique=True),
        ),
    ]
