# Generated by Django 3.1.6 on 2021-02-24 22:57

from django.db import migrations


def migrate_teams_stats_to_teaminfo_objects(apps, schema_editor):
    Team = apps.get_model('scoreboard', 'Team')
    League = apps.get_model('scoreboard', 'League')
    TeamInfo = apps.get_model('scoreboard', 'TeamInfo')

    hfl2020 = League.objects.create(
        name='ХФЛ',
        years='2020',
        active=False
    )

    teams2020 = Team.objects.all()

    for team in teams2020:
        TeamInfo.objects.create(
            league=hfl2020,
            team=team,
            place=team.place,
            games=team.games,
            wins=team.wins,
            draws=team.draws,
            losses=team.losses,
            goals_scored=team.goals_scored,
            goals_conceded=team.goals_conceded,
            points=team.points
        )
    


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_auto_20210225_0048'),
    ]

    operations = [
        migrations.RunPython(migrate_teams_stats_to_teaminfo_objects, reverse_code=migrations.RunPython.noop)
    ]
