# Generated by Django 3.1.6 on 2021-02-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_auto_20210225_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_scored',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='place',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
    ]
