# Generated by Django 3.2.5 on 2021-11-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0011_auto_20210416_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='medal',
            field=models.PositiveIntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], null=True),
        ),
    ]
