name: Unit-Testing-After-Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Create test DB
        run: |
          sudo apt update
          sudo apt install python-pip python-dev libpq-dev postgresql postgresql-contrib nginx curl
          sudo -u postgres psql
          CREATE DATABASE tempfc;
          CREATE USER tempfcuser WITH PASSWORD 'Gp>kw6w/S])k%?[Q';
          ALTER ROLE tempfcuser SET client_encoding TO 'utf8';
          ALTER ROLE tempfcuser SET default_transaction_isolation TO 'read committed';
          ALTER ROLE tempfcuser SET timezone TO 'UTC';
          GRANT ALL PRIVILEGES ON DATABASE tempfc TO tempfcuser;
          \q
      - name: Pip Upgrade
        run: pip3 install --upgrade setuptools
      - name: ADD requirements
        run: pip3 install -r requirements.txt
      - name: Run postgres
        run: sudo service postgresql start
      - name: DB Migrations
        run: python3 manage.py migrate
      - name: Run tests
        run: python3 manage.py test

      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          status: ${{ job.status }}
