name: Unit-Testing-After-Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
#      - name: Pip Upgrade
 #       run: pip install -U pip
      - name: ADD requirements
        run: pip3 install -r requirements.txt
      - name: DB Migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test

      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          status: ${{ job.status }}
